### ISSUE TITLE
example-get:started: make plot files smaller

### ISSUE THREAD

**Issue by shcheklein** [iterative/example-repos-dev#49]
> Yeah, technically plotting precision-recall gets a bit weird with fewer points, but as long as we keep a reasonably large number of points, it shouldn’t be a noticeable issue. We can do the same with roc.json

> Agree that we need a good number of data points. It should be enough for Studio to cut the size 2x. And it should not be noticeable for the curve quality (I hope :slightly_smiling_face: ).

> roc.json is very small 56Kb. No need to optimize.

> Oh weird, it looks like sklearn automatically cuts it down to an optimal size for roc but not prc.

> @ivan Let me know if you want me to regenerate it. I don’t know how the additional branch was added, but I can at least take care of master if needed.

cc @dberenbaum @dmpetrov

**Comment by dberenbaum** [comment]
Currently blocked by https://github.com/iterative/dvc/issues/6078

**Comment by dberenbaum** [comment]
Depends on #51

**Comment by dberenbaum** [comment]
Should we wait for #50 before pushing to example-get-started? Otherwise, I think the branches will diverge.

**Comment by shcheklein** [comment]
I think #50 would take make me a bit to implement properly. Let's push it when we ready and let me know- I'll try to create all the needed PRs, branches.

**Comment by dberenbaum** [comment]
Okay, updated https://github.com/iterative/example-get-started

**Comment by dberenbaum** [comment]
There was confusion over why some experiments generate very small `prc.json` files (every experiment up to and including `bigrams-experiment`) and other experiments generate very large `prc.json` files (like `random-forest-experiments`). The reason is that the model parameters for some are generating very few unique predictions (27 for `bigrams-experiment` vs. 4,372 for `random-forest-experiments). Precision and recall can only be calculated for each unique prediction value, so this limits the size of the file and corresponding plot. Without diving too deep into model explainability, the reason for so few unique predictions seems to be due to having `min_sample_split=2` for a lot of the initial experiments, which results in overfitting and basically mapping test samples to the most similar training sample.
