### ISSUE TITLE
rename `get-started-experiments` to `dvc-example-experiments`. 

### ISSUE THREAD

**Issue by iesahin** [iterative/example-repos-dev#79]
We have a new naming convention for the example projects and the latter name seems more descriptive.

**Comment by shcheklein** [comment]
@casperdcl what do we need from to make this repo useful for CML happy-path? 

@iesahin @casperdcl as we discussed can we make it `example-experiments` that would cover basic scenarios with predefined language (python), predefined framework (let's say tensorflow for now). It would have CML action from the first (?) commit that could be run if it's needed (and may be even runs automatically).

Then it'll be a good repo that we can even meaningfully present in Studio?

What do we need to make it substantially useful for CML?

**Comment by casperdcl** [comment]
@shcheklein I can see this issue is closed as the repo has been renamed in #82. However, regarding the other points you mention:


- the CML use case (specifically auto-push checkpoints) is significantly different from any of the DVC use cases (CC @DavidGOrtega)
  - it also requires significant additional config (workflow.yaml, creds for cloud compute, creds for remote storage, additional env vars)
- placing the CML example in the same repo as DVC examples is very confusing to users. Switching branches is an unnecessary complexity on top of an already complex example.

I'd strongly suggest the CML case is pushed to a different repo (`example-cml-experiments`, with separate branches for with & without `dvc`) rather than more branches in `example-dvc-experiments`
